language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
  - find ./scripts -name "*.sh" -exec chmod +x {} \;
  - ./scripts/show-dotnet-info.sh

  # Download script to install dotnet cli
  - curl -L --create-dirs https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.sh -o ./scripts/obtain/install.sh
  - find ./scripts -name "*.sh" -exec chmod +x {} \;
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  # use bash to workaround bug https://github.com/dotnet/cli/issues/1725
  - sudo bash ./scripts/obtain/install.sh --channel "preview" --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR" --no-path
  # add dotnet to PATH
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
script:
  - chmod +x ./build.sh
  - ./build.sh
env:
  - BUILDING_ON_PLATFORM=unix
