language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openssl; brew link --force openssl; fi

install:
  # Download .NET Core SDK and add to PATH
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
  - mkdir -p "$DOTNET_INSTALL_DIR"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then DOTNET_SDK_URL=https://go.microsoft.com/fwlink/?LinkID=809128; else DOTNET_SDK_URL=https://go.microsoft.com/fwlink/?LinkID=809129; fi
  - curl -L "$DOTNET_SDK_URL" | tar -xzv -C "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
os:
  - linux
  - osx
osx_image: xcode7.1
script:
  - chmod +x ./build.sh
  - ./build.sh
env:
  - DOTNET_SDK_URL=https://go.microsoft.com/fwlink/?LinkID=809129
notifications:
  email: false
