language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.0-preview2-003121

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openssl; mkdir -p /usr/local/lib; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
os:
  - linux
  - osx
osx_image: xcode7.3
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh
notifications:
  email: false
